columns:
  having_IP_Address:
    type: integer
    description: "Presence of IP address in URL (-1, 0, 1)"

  URL_Length:
    type: integer
    description: "Length category of URL (-1, 0, 1)"

  Shortining_Service:
    type: integer
    description: "Use of URL shortening service (-1, 0, 1)"

  having_At_Symbol:
    type: integer
    description: "Presence of @ symbol in URL (-1, 0, 1)"

  double_slash_redirecting:
    type: integer
    description: "Presence of // for redirection (-1, 0, 1)"

  Prefix_Suffix:
    type: integer
    description: "Presence of - in domain (-1, 0, 1)"

  having_Sub_Domain:
    type: integer
    description: "Number of sub domains (-1, 0, 1)"

  SSLfinal_State:
    type: integer
    description: "SSL certificate state (-1, 0, 1)"

  Domain_registeration_length:
    type: integer
    description: "Domain registration length (-1, 0, 1)"

  Favicon:
    type: integer
    description: "Favicon presence (-1, 0, 1)"

  port:
    type: integer
    description: "Unusual port usage (-1, 0, 1)"

  HTTPS_token:
    type: integer
    description: "HTTPS token in domain (-1, 0, 1)"

  Request_URL:
    type: integer
    description: "Request URL legitimacy (-1, 0, 1)"

  URL_of_Anchor:
    type: integer
    description: "Anchor URL usage (-1, 0, 1)"

  Links_in_tags:
    type: integer
    description: "Links in tags (-1, 0, 1)"

  SFH:
    type: integer
    description: "Server Form Handler (-1, 0, 1)"

  Submitting_to_email:
    type: integer
    description: "Submission to email (-1, 0, 1)"

  Abnormal_URL:
    type: integer
    description: "Abnormal URL characteristics (-1, 0, 1)"

  Redirect:
    type: integer
    description: "Redirect usage (-1, 0, 1)"

  on_mouseover:
    type: integer
    description: "Mouseover event handling (-1, 0, 1)"

  RightClick:
    type: integer
    description: "Right-click functionality (-1, 0, 1)"

  popUpWidnow:
    type: integer
    description: "Pop-up window usage (-1, 0, 1)"

  Iframe:
    type: integer
    description: "IFrame usage (-1, 0, 1)"

  age_of_domain:
    type: integer
    description: "Domain age category (-1, 0, 1)"

  DNSRecord:
    type: integer
    description: "DNS record availability (-1, 0, 1)"

  web_traffic:
    type: integer
    description: "Web traffic ranking (-1, 0, 1)"

  Page_Rank:
    type: integer
    description: "PageRank value (-1, 0, 1)"

  Google_Index:
    type: integer
    description: "Google index status (-1, 0, 1)"

  Links_pointing_to_page:
    type: integer
    description: "Number of links pointing to page (-1, 0, 1)"

  Statistical_report:
    type: integer
    description: "Statistical report (UriBlacklist, PhishTank) (-1, 0, 1)"

  Result:
    type: integer
    description: "Target variable: Phishing classification (-1: phishing, 1: legitimate)"

numerical_columns:
  - having_IP_Address
  - URL_Length
  - Shortining_Service
  - having_At_Symbol
  - double_slash_redirecting
  - Prefix_Suffix
  - having_Sub_Domain
  - SSLfinal_State
  - Domain_registeration_length
  - Favicon
  - port
  - HTTPS_token
  - Request_URL
  - URL_of_Anchor
  - Links_in_tags
  - SFH
  - Submitting_to_email
  - Abnormal_URL
  - Redirect
  - on_mouseover
  - RightClick
  - popUpWidnow
  - Iframe
  - age_of_domain
  - DNSRecord
  - web_traffic
  - Page_Rank
  - Google_Index
  - Links_pointing_to_page
  - Statistical_report
  - Result
